plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/YB/Downloads/garyshker_deploy"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/ru/*"
to = "/:splat?lang=ru"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/kz/*"
to = "/:splat?lang=kz"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/en/*"
to = "/:splat?lang=en"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/ru"
to = "/"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/kz"
to = "/?lang=kz"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/en"
to = "/?lang=en"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]